name: disdrometer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  convex_bottom_bar: ^2.4.1
  flare_flutter: ^2.0.5
  flutter_staggered_grid_view: ^0.3.0
  flare_splash_screen: ^3.0.1
  flutter_swiper: ^1.1.6
  flutter_google_places: ^0.2.5
  place_picker: ^0.9.14
  google_maps_webservice: ^0.0.17
  page_transition: ^1.1.5
  geocoder: ^0.2.1
  google_maps_flutter: ^0.5.28+1
  font_awesome_flutter: ^8.8.1
  http: ^0.12.2
  date_time_format: ^1.0.0+4
  geolocator: ^5.3.2+2

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - assets/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
